// code by jph
package ch.ethz.idsc.tensor.io;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;

import ch.ethz.idsc.tensor.Tensor;

/** import tensor expression that was created by {@link Put}.
 * The format is similar to Object::toString and readable in any text editor.
 * 
 * <p>The file format is intended for data exchange between
 * Mathematica and the tensor library.
 * 
 * <p>example content
 * <pre>
 * {{2 + 9*I, 3 - I, 3 - 2.423*I},
 * {(23 + I) / 4, 3.1415}, {}}
 * </pre>
 * 
 * <p>files generated by Tensor::Put, and Mathematica::Put
 * are suitable for import using Get.
 * 
 * <p>the format does not specify or require any particular
 * file extension. Mathematica also does not define an extension
 * for this format.
 * 
 * <p>inspired by
 * <a href="https://reference.wolfram.com/language/ref/Get.html">Get</a> */
public enum Get {
  ;
  /** @param file source
   * @return
   * @throws IOException */
  public static Tensor of(File file) throws IOException {
    try (InputStream inputStream = new FileInputStream(file)) {
      return of(inputStream);
    }
  }

  /** @param inputStream source
   * @return */
  public static Tensor of(InputStream inputStream) {
    return MathematicaFormat.parse(ReadLine.of(inputStream));
  }
}
